# Site settings
title: just a blog
SEOTitle: 随笔
header-img: img/home-blog.jpg
email: alexneko1224@gmail.com
description: "生活与学习的笔记"
keywords: " Blog, 博客, 个人网站, ALexneko1224"
url: "https://github.com/Alexneko1224/Alexneko1224.github.io.git"              # your host, for absolute URL
baseurl: "/"         # for example, '/blog' if your blog hosted on 'host/blog'



# baidu-site-verification : xxxxxxxxx
# google-site-verification : xxxxxxxxx

# Publish posts or collection documents with a future date.
future: true
license: true

# SNS settings
RSS: false
weibo_username:     袜酱袜酱
#zhihu_username:     huxpro
github_username:    Alexneko1224
bilibili_username:  阿米娅awsl
#facebook_username:  huxpro
#jianshu_username:   xxxxxxx
#linkedin_username:  firstname-lastname-idxxxx


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 7 # 一页多少post
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true
# if you want to customize anchor. check out line:181 of `post.html`
# If you haven't timezone issue (e.g. #68) in China, comment to this:
timezone: CN



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# comment settings
#disqus_username: here
livere_uid : "MTAyMC80MjU0Ni8xOTA5Mw=="

# Netease settings
netease_comment: false

# gitalk:
#取消注释全部这一大块来使用gitalk
#比起使用gitalk，为什么不试试livere？
  # clientID: #clientID here
  # clientSecret:     #clientSecret here
  # repo:
  # owner: #github user name
  # admin:
  # distractionFreeMode: true #是否启用类FB的阴影遮罩


# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id:  # Format: UA-xxxxxx-xx
#ga_domain: auto



# Sidebar settings
#注释全部这一块来不使用侧边栏
sidebar:
   about-description: "只是个小白"
   avatar: /img/Alexneko1224.jpg
   # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tagscondition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "just a blog",
        href: "https://steve02081504.github.io/"
    }
    ,{
        title: "某兔子の御用花园",
        href: "https://www.rabbittu.com/"
    }
    ,{
        title: "laugh\'s online",
        href: "https://laugh0608.github.io"
    }
    ,{
        title: "SunQH",
        href: "https://sunqinghu.github.io/"
    }
    #,{
    #    title: "",
    #    href: ""
    #}
]

theme: jekyll-theme-cayman
